swagger: "2.0"
info:
  title: "FlaskAPI"
  description: "Endpoint to create a user"
  version: "1.0.0"
host: "localhost:5000"
basePath: "/"
schemes:
  - "http"
produces:
  - "application/json"
paths:
  /user:
    post:
      summary: "Create a user"
      parameters:
        - name: "name"
          in: "formData"
          description: "Name of the user"
          required: true
          type: "string"
        - name: "email"
          in: "formData"
          description: "Email of the user"
          required: true
          type: "string"
        - name: "password"
          in: "formData"
          description: "Password of the user"
          required: true
          type: "string"
      responses:
        201:
          description: "User created successfully"
